// packages/react/src/pages/resources/edit.tsx
import { ResourceEditView } from "../../components/views/resources/edit.js";
import { RecordProvider } from "../../providers/record.js";
import { ResourceProvider } from "../../providers/resource.js";

export default function Page({
  resource,
  record,
}: {
  resource: string;
  record: any;
}) {
  return (
    <ResourceProvider resource={resource}>
      <RecordProvider record={record}>
        <ResourceEditView />
      </RecordProvider>
    </ResourceProvider>
  );
}

// resources/pages/resources/edit.vue
<script setup lang="ts">
import { Resource, ResourceRecord } from '../../types'
import Edit from '../../components/resource/views/edit.vue'
import ProvideResource from '../../components/resource/provide-resource.vue'
import Layout from '../../layouts/app.vue'

defineOptions({
  layout: Layout,
})

defineProps<{
  resource: Resource
  record: ResourceRecord
}>()
</script>

<template>
  <ProvideResource :resource="resource">
    <Edit :record="record" />
  </ProvideResource>
</template>
